# .github/workflows/maven-build.yml

name: Maven Build

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
